FROM golang:1.24.9-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o simulator ./cmd/simulator

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/simulator .
COPY .env .env
EXPOSE 50051

CMD ["./simulator"]
