[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
zk_lend = "5yyTV7F75vyHXn2kWQZ7XxPoZ6GNEzPgyBFjiUF5dXwc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/settorka/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
