[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
openrate = "7baz5aqHG5CUPqpsavhXDgTmHkYgKVthDuuFkT3Fbdt9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/settorka/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[programs.devnet]
openrate = "7baz5aqHG5CUPqpsavhXDgTmHkYgKVthDuuFkT3Fbdt9"
