// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/builder.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BundleSubmission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BundleId      string                 `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	ProfitEth     float64                `protobuf:"fixed64,2,opt,name=profit_eth,json=profitEth,proto3" json:"profit_eth,omitempty"`
	Txs           []string               `protobuf:"bytes,3,rep,name=txs,proto3" json:"txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleSubmission) Reset() {
	*x = BundleSubmission{}
	mi := &file_proto_builder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleSubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleSubmission) ProtoMessage() {}

func (x *BundleSubmission) ProtoReflect() protoreflect.Message {
	mi := &file_proto_builder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleSubmission.ProtoReflect.Descriptor instead.
func (*BundleSubmission) Descriptor() ([]byte, []int) {
	return file_proto_builder_proto_rawDescGZIP(), []int{0}
}

func (x *BundleSubmission) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *BundleSubmission) GetProfitEth() float64 {
	if x != nil {
		return x.ProfitEth
	}
	return 0
}

func (x *BundleSubmission) GetTxs() []string {
	if x != nil {
		return x.Txs
	}
	return nil
}

type BuildResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BlockHash          string                 `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Included           bool                   `protobuf:"varint,2,opt,name=included,proto3" json:"included,omitempty"`
	InclusionReason    string                 `protobuf:"bytes,3,opt,name=inclusion_reason,json=inclusionReason,proto3" json:"inclusion_reason,omitempty"`
	InclusionLatencyMs int64                  `protobuf:"varint,4,opt,name=inclusion_latency_ms,json=inclusionLatencyMs,proto3" json:"inclusion_latency_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BuildResult) Reset() {
	*x = BuildResult{}
	mi := &file_proto_builder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResult) ProtoMessage() {}

func (x *BuildResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_builder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResult.ProtoReflect.Descriptor instead.
func (*BuildResult) Descriptor() ([]byte, []int) {
	return file_proto_builder_proto_rawDescGZIP(), []int{1}
}

func (x *BuildResult) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *BuildResult) GetIncluded() bool {
	if x != nil {
		return x.Included
	}
	return false
}

func (x *BuildResult) GetInclusionReason() string {
	if x != nil {
		return x.InclusionReason
	}
	return ""
}

func (x *BuildResult) GetInclusionLatencyMs() int64 {
	if x != nil {
		return x.InclusionLatencyMs
	}
	return 0
}

var File_proto_builder_proto protoreflect.FileDescriptor

const file_proto_builder_proto_rawDesc = "" +
	"\n" +
	"\x13proto/builder.proto\x12\abuilder\"`\n" +
	"\x10BundleSubmission\x12\x1b\n" +
	"\tbundle_id\x18\x01 \x01(\tR\bbundleId\x12\x1d\n" +
	"\n" +
	"profit_eth\x18\x02 \x01(\x01R\tprofitEth\x12\x10\n" +
	"\x03txs\x18\x03 \x03(\tR\x03txs\"\xa5\x01\n" +
	"\vBuildResult\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\tR\tblockHash\x12\x1a\n" +
	"\bincluded\x18\x02 \x01(\bR\bincluded\x12)\n" +
	"\x10inclusion_reason\x18\x03 \x01(\tR\x0finclusionReason\x120\n" +
	"\x14inclusion_latency_ms\x18\x04 \x01(\x03R\x12inclusionLatencyMs2Q\n" +
	"\x0eBuilderService\x12?\n" +
	"\fSubmitBundle\x12\x19.builder.BundleSubmission\x1a\x14.builder.BuildResultB\x17Z\x15mev-relay/internal/pbb\x06proto3"

var (
	file_proto_builder_proto_rawDescOnce sync.Once
	file_proto_builder_proto_rawDescData []byte
)

func file_proto_builder_proto_rawDescGZIP() []byte {
	file_proto_builder_proto_rawDescOnce.Do(func() {
		file_proto_builder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_builder_proto_rawDesc), len(file_proto_builder_proto_rawDesc)))
	})
	return file_proto_builder_proto_rawDescData
}

var file_proto_builder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_builder_proto_goTypes = []any{
	(*BundleSubmission)(nil), // 0: builder.BundleSubmission
	(*BuildResult)(nil),      // 1: builder.BuildResult
}
var file_proto_builder_proto_depIdxs = []int32{
	0, // 0: builder.BuilderService.SubmitBundle:input_type -> builder.BundleSubmission
	1, // 1: builder.BuilderService.SubmitBundle:output_type -> builder.BuildResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_builder_proto_init() }
func file_proto_builder_proto_init() {
	if File_proto_builder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_builder_proto_rawDesc), len(file_proto_builder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_builder_proto_goTypes,
		DependencyIndexes: file_proto_builder_proto_depIdxs,
		MessageInfos:      file_proto_builder_proto_msgTypes,
	}.Build()
	File_proto_builder_proto = out.File
	file_proto_builder_proto_goTypes = nil
	file_proto_builder_proto_depIdxs = nil
}
