// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/simulator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BundleId      string                 `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	Txs           []string               `protobuf:"bytes,2,rep,name=txs,proto3" json:"txs,omitempty"`
	TargetBlock   string                 `protobuf:"bytes,3,opt,name=target_block,json=targetBlock,proto3" json:"target_block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleRequest) Reset() {
	*x = BundleRequest{}
	mi := &file_proto_simulator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleRequest) ProtoMessage() {}

func (x *BundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleRequest.ProtoReflect.Descriptor instead.
func (*BundleRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulator_proto_rawDescGZIP(), []int{0}
}

func (x *BundleRequest) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *BundleRequest) GetTxs() []string {
	if x != nil {
		return x.Txs
	}
	return nil
}

func (x *BundleRequest) GetTargetBlock() string {
	if x != nil {
		return x.TargetBlock
	}
	return ""
}

type BundleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BundleId      string                 `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	ProfitEth     float64                `protobuf:"fixed64,2,opt,name=profit_eth,json=profitEth,proto3" json:"profit_eth,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleResponse) Reset() {
	*x = BundleResponse{}
	mi := &file_proto_simulator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleResponse) ProtoMessage() {}

func (x *BundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleResponse.ProtoReflect.Descriptor instead.
func (*BundleResponse) Descriptor() ([]byte, []int) {
	return file_proto_simulator_proto_rawDescGZIP(), []int{1}
}

func (x *BundleResponse) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *BundleResponse) GetProfitEth() float64 {
	if x != nil {
		return x.ProfitEth
	}
	return 0
}

func (x *BundleResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *BundleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BundleResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_simulator_proto protoreflect.FileDescriptor

const file_proto_simulator_proto_rawDesc = "" +
	"\n" +
	"\x15proto/simulator.proto\x12\tsimulator\"a\n" +
	"\rBundleRequest\x12\x1b\n" +
	"\tbundle_id\x18\x01 \x01(\tR\bbundleId\x12\x10\n" +
	"\x03txs\x18\x02 \x03(\tR\x03txs\x12!\n" +
	"\ftarget_block\x18\x03 \x01(\tR\vtargetBlock\"\x9d\x01\n" +
	"\x0eBundleResponse\x12\x1b\n" +
	"\tbundle_id\x18\x01 \x01(\tR\bbundleId\x12\x1d\n" +
	"\n" +
	"profit_eth\x18\x02 \x01(\x01R\tprofitEth\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason2Z\n" +
	"\x11SimulationService\x12E\n" +
	"\x0eSimulateBundle\x12\x18.simulator.BundleRequest\x1a\x19.simulator.BundleResponseB\x17Z\x15mev-relay/internal/pbb\x06proto3"

var (
	file_proto_simulator_proto_rawDescOnce sync.Once
	file_proto_simulator_proto_rawDescData []byte
)

func file_proto_simulator_proto_rawDescGZIP() []byte {
	file_proto_simulator_proto_rawDescOnce.Do(func() {
		file_proto_simulator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_simulator_proto_rawDesc), len(file_proto_simulator_proto_rawDesc)))
	})
	return file_proto_simulator_proto_rawDescData
}

var file_proto_simulator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_simulator_proto_goTypes = []any{
	(*BundleRequest)(nil),  // 0: simulator.BundleRequest
	(*BundleResponse)(nil), // 1: simulator.BundleResponse
}
var file_proto_simulator_proto_depIdxs = []int32{
	0, // 0: simulator.SimulationService.SimulateBundle:input_type -> simulator.BundleRequest
	1, // 1: simulator.SimulationService.SimulateBundle:output_type -> simulator.BundleResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_simulator_proto_init() }
func file_proto_simulator_proto_init() {
	if File_proto_simulator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_simulator_proto_rawDesc), len(file_proto_simulator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_simulator_proto_goTypes,
		DependencyIndexes: file_proto_simulator_proto_depIdxs,
		MessageInfos:      file_proto_simulator_proto_msgTypes,
	}.Build()
	File_proto_simulator_proto = out.File
	file_proto_simulator_proto_goTypes = nil
	file_proto_simulator_proto_depIdxs = nil
}
